### ISSUE TITLE
senate labeling issue, not urgent

### ISSUE THREAD

**Issue by BGranberg** [agrc/lt-gov-political-districts#2]
3 labels appear for the senate districts in northern utah, see attachment

![screen shot 2017-04-04 at 8 47 10 am](https://cloud.githubusercontent.com/assets/1766038/24665248/1122ef8e-191a-11e7-82fc-adb074e398c0.png)

**Comment by stdavis** [comment]
This was a data issue (forklift) and _should_ be fixed in the morning.
