### ISSUE TITLE
production dns

### ISSUE THREAD

**Issue by stdavis** [agrc/lt-gov-political-districts#8]
We need to request a production DNS for this project: `politicaldistricts.ugrc.utah.gov`

@nathankota Can you help with the DNS request?

**Comment by nathankota** [comment]
@stdavis It sounds like that is already the chosen prod DNS, correct?

**Comment by stdavis** [comment]
Yes, just because the dev DNS has already been chosen.

**Comment by nathankota** [comment]
INC1493876

**Comment by stdavis** [comment]
We need this custom dns added to the firebase hosting for this project similar to: https://github.com/agrc/deq-spills/issues/62.

**Comment by nathankota** [comment]
@stdavis what is the firebase hosting info for this, like `ut-dts-agrc-districts-prod` (or something else in place of the `districts` part?

**Comment by stdavis** [comment]
`ut-dts-agrc-pol-districts-prod`

**Comment by nathankota** [comment]
INC1495266

**Comment by nathankota** [comment]
DNS has been added to firebase hosting. There appear to be some issues with the basemaps, district pdf maps and find location, but printing worked for me.

**Comment by stdavis** [comment]
I'm working on fixing all of that. Thanks for getting the DNS working!
